### ISSUE TITLE
any genshin 3.5 soon?

### ISSUE THREAD

**Issue by A-begger** [zeroday0619/MyLittleLutrisScripts#12]

**Comment by scorninpc** [comment]
done! https://github.com/zeroday0619/MyLittleLutrisScripts/commit/19a89afbc73f06ad44e720f2c29a387eb620e135

don't forget this is for test only. Don't play with your main account for some days

**Comment by kotsmotritnastul** [comment]
pls say when it will be safe to use.

**Comment by scorninpc** [comment]
> pls say when it will be safe to use.

Will be unlocked @ 4/march. Safe.. I think never!

**Comment by Ash3781** [comment]
> Safe... I think never!

Realistically speaking, how likely is it (not just for this version, i mean in general), to be banned or something for just playing it on linux? not doing any other modifications to the game other than being able to play it on linux?

**Comment by scorninpc** [comment]
> Realistically speaking, how likely is it (not just for this version, i mean in general), to be banned or something for just playing it on linux? not doing any other modifications to the game other than being able to play it on linux?

You are disabling security system of the game. Maybe you are just playing, but people do bots to play alone and make money with that

but I don't think this is the place to discuss that

**Comment by Ash3781** [comment]
May I ask if that means the script is safe to use if I don't modify it any further than the script does?

**Comment by scorninpc** [comment]
> May I ask if that means the script is safe to use if I don't modify it any further than the script does?

the problem is not the script. it is safe to use. but game developers can easily identify if you are using guard or not, and ban your account. It never happens, but.....

**Comment by Ash3781** [comment]
Then I'm even more confused, how is it going to be "safer" to use in a couple of days, I'm still not using their guard system? Or is it just that it does not know that it is off and thereby safer?

**Comment by scorninpc** [comment]
I never told that is it going to be "safer". It will be unlocked, confirming that the block guard works

**Comment by Ash3781** [comment]
I'm sorry, I misread your first and second message, may I ask what difference it makes to wait until it is "unlocked"?

**Comment by scorninpc** [comment]
> I'm sorry, I misread your first and second message, may I ask what difference it makes to wait until it is "unlocked"?

i dont know, i'm not the dev

**Comment by zeroday0619** [comment]
> I'm sorry, I misread your first and second message, may I ask what difference it makes to wait until it is "unlocked"?

This means that the stability test has been successfully performed in the internal test.

**Comment by Ash3781** [comment]
So the only thing that might change from waiting till 4th is more stability? The risk of "getting cought" stays the same or does it mean if it crashes it sends a crash report to their devs or whatever and they see that the guard thingy is off?

**Comment by CryptoGladi** [comment]
@Ash3781 I checked the patch on my account. I've been playing for 2 days now and I'm fine, but I **can't say for sure that your account will not be blocked**.

**Comment by Ash3781** [comment]
Do you know if that probability of being blocked/banned will decrease if we wait for an official-inofficial patch or if it just means the game is less likely to crash?

**Comment by zeroday0619** [comment]
We are not responsible for anything that happens as a result of using this. However, in order to mitigate possible risks from these risks, the release is made after going through an internal verification process.

**Comment by CryptoGladi** [comment]
@Ash3781 Personally, when a new version of the game comes out, I immediately go to this repository and wait for the new patch to commit. But I'd **rather** listen zeroday0619. He's right.

**Comment by Ash3781** [comment]
I think i get it now, thank you all for explaining it to me, could someone please ping me if the verification process is finished?

**Comment by zeroday0619** [comment]
> I think i get it now, thank you all for explaining it to me, could someone please ping me if the verification process is finished?

ok

**Comment by iambeingtracked** [comment]
https://forums.lutris.net/t/genshin-impact-3-5-or-new-versions/17348/3

Here's a discussion on Lutris forums if you're wondering.

Any info on when will the verification process finish?

**Comment by Ash3781** [comment]
Any news on the test?

**Comment by CryptoGladi** [comment]
@Ash3781 My account has not been banned yet.

**Comment by iambeingtracked** [comment]
That's great, but does the development team have any news? I want to know about the verification process and how's it going

**Comment by Ash3781** [comment]
Weren't you the one saying you'd rather listen to the repo's owner? I don't want to test the patch by wether (I don't know if this is spelt correctly) or not I am able to still login tomorrow

**Comment by CryptoGladi** [comment]
I think the **best thing** to do is just wait. You can use my words as a **little** test of this patch.

**Comment by zeroday0619** [comment]
@Ash3781 done!

**Comment by zeroday0619** [comment]
sorry. I checked a bit late.

**Comment by Ash3781** [comment]
Is it already available via lutris or do I have to install it manually somehow?

**Comment by iambeingtracked** [comment]
> @Ash3781 done!

So it the verification process finished? Will there be new commits to the repo or is the previous archive fine too?

**Comment by zeroday0619** [comment]
yes

**Comment by iambeingtracked** [comment]
So I can now just download the previously published archive and play? No new commits?

**Comment by Ash3781** [comment]
I just replaced all the files in the gi_patch folder, however lutris gives me this error: 

```
Started initial process 6779 from /home/ash/Games/genshin-impact/drive_c/gi_patch.sh
Start monitoring process.
Gtk-Message: 14:32:11.536: Failed to load module "appmenu-gtk-module"
valeur de la variable CHOICE:  Patch Genshin Impact
xterm: No absolute path found for shell: ex_apatch.sh
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
DEBUG    2023-03-04 14:32:16,037 [command.on_stop:195]:Process 6777 has terminated with code 0
```
and i do not know which language that is in between, not my system language for sure

**Comment by zeroday0619** [comment]
> appmenu-gtk-module

`sudo apt-get install appmenu-gtk2-module appmenu-gtk3-module`

**Comment by Ash3781** [comment]
i'm on arch, but that is not the problem, i think the xterm line is

**Comment by Ash3781** [comment]
can i somehow manually start the patch script without needing to rely on xterm?

**Comment by zeroday0619** [comment]
Try replacing it with this one
https://raw.githubusercontent.com/zeroday0619/MyLittleLutrisScripts/master/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/gi_patch.sh

**Comment by Ash3781** [comment]
thank you, that did it, tho just to be sure i also added the upload url's to my dns's blocklist

**Comment by Ash3781** [comment]
welp... first ever genshin crash just happened, my dns server let an request for `url` through, do i need to worry about that?

**Comment by scorninpc** [comment]
> https://forums.lutris.net/t/genshin-impact-3-5-or-new-versions/17348/3
> 
> Here's a discussion on Lutris forums if you're wondering.
> 
> Any info on when will the verification process finish?

people surprise me how much they are stupid! Every day, every one telling to not provide links or share it, and what ppl do? share it on wrong place

this repo is getting bigger. So fav this link, i'll put every vesion here too https://1drv.ms/u/s!AkcHTm4bqBexc6ArJgYoXAJrFzM?e=wffv7N

@zeroday0619, if this is a problem, tell me and i'll remove this comment

ps: sorry for this comment
