### ISSUE TITLE
Progress of the 3.6.0 patch

### ISSUE THREAD

**Issue by zeroday0619** [zeroday0619/MyLittleLutrisScripts#13]
Official release date: 12 Apr (pre-download 10 Apr)

Patch completion/script unlock: 15 Apr ¹

----
¹) Might also take longer. New code is an unknown time factor.

**Comment by lqSky7** [comment]
Thank you for your work. I'm waiting

**Comment by oritwoen** [comment]
@zeroday0619 what this patch do? Why is needed for playing Genshin on Linux?

I saw that on official Lutris page Genshin Impact 3.5 (probably 3.6 also) work without patching.

https://lutris.net/games/genshin-impact/

```
Standard Version
- This installs a clean version of the game with no scripts or patches or anti-cheat workarounds.
```

**Comment by kotsmotritnastul** [comment]
@oritwoen did you test it without patches?

**Comment by zeroday0619** [comment]
@oritwoen @kotsmotritnastul 
Technical information cannot be mentioned. 
As far as I can tell, kernel level anti-cheats can't work in wine.

**Comment by scorninpc** [comment]
> I saw that on official Lutris page Genshin Impact 3.5 (probably 3.6 also) work without patching.

@oritwoen: as far I know, the same method are used to patch, but still needed. Did you try run without patch? its works?

I'll try to commit 3.6 today ok?

**Comment by khjde1207** [comment]
https://lutris.net/games/genshin-impact/ 

I tested it, but it didn't work.

**Comment by lqSky7** [comment]
> @zeroday0619 what this patch do? Why is needed for playing Genshin on Linux?
> 
> I saw that on official Lutris page Genshin Impact 3.5 (probably 3.6 also) work without patching.
> 
> https://lutris.net/games/genshin-impact/
> 
> ```
> Standard Version
> - This installs a clean version of the game with no scripts or patches or anti-cheat workarounds.
> ```

It does not work. I've already made a report to lutris

**Comment by scorninpc** [comment]
### Done guys!

https://github.com/zeroday0619/MyLittleLutrisScripts/commit/9bc1735f78e3dda28bc84af5a2b6d5a64d6f6cd7

### Testing patches for 3.6.0 are done


`As usual, please use only testing accounts until the patch is confirmed working. If everything goes well, patch unlock will be on 15 April.`

**Comment by Ash3781** [comment]
Hey, just wanted to update the game already so if it is finished i don't have to do that then, however since i got a new m.2 i had to reinstall lutris and imported the game (it's on an dedicated ssd for games), however there is no option anymore to launch a script, even after "upgrading" it to the 3.5 patch that lutris offers, how do i get that back so when the script will be unlocked tomorrow i can execute it?

**Comment by khjde1207** [comment]
path : genshin-impact/drive_c/

[gi_menu.bat](https://github.com/zeroday0619/MyLittleLutrisScripts/blob/master/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/gi_menu.bat)
[gi_patch.sh](https://github.com/zeroday0619/MyLittleLutrisScripts/blob/master/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/gi_patch.sh)

/home/khjde1207/Games/genshin-impact/drive_c/gi_patch/

[gi_patch_360.zip](https://github.com/zeroday0619/MyLittleLutrisScripts/blob/master/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/gi_patch_360.zip)

unzip gi_patch_360.zip

lutris Game options 

Executable  : [path to game]/genshin-impact/drive_c/windows/syswow64/wineconsole.exe
Arguments :  c:\\gi_menu.bat

**Comment by yeziditruth** [comment]
I'm not sure what to look for short of an account ban, but I'm happy to report that nothing has happened in a good six or so hours of gameplay on an alt acct. Are there any sort of logs or reports that would be useful for the project even without having experienced any problems?

**Comment by oritwoen** [comment]
> @zeroday0619 what this patch do? Why is needed for playing Genshin on Linux?
> 
> I saw that on official Lutris page Genshin Impact 3.5 (probably 3.6 also) work without patching.
> 
> https://lutris.net/games/genshin-impact/
> 
> ```
> Standard Version
> - This installs a clean version of the game with no scripts or patches or anti-cheat workarounds.
> ```

About this, I don't tested clean game. Only saw `playable` label. If don't work I believe you guys. Someone must have assigned the wrong label.

**Comment by iambeingtracked** [comment]
How is the patch unlock process going?

**Comment by scorninpc** [comment]
> How is the patch unlock process going?

the lock process is only some comments and a `pause` on script, to force you read the comment.

here we post the path without the `pause`, so the path locked and unlocked is the same

**Comment by iambeingtracked** [comment]
> > How is the patch unlock process going?
> 
> the lock process is only some comments and a `pause` on script, to force you read the comment.
> 
> here we post the path without the `pause`, so the path locked and unlocked is the same

So do I just download the current thing and edit the script? I mean, on ver. 3.5 there was a new archive, does it matter?

**Comment by Ash3781** [comment]
Is there any new information on the eta?

**Comment by scorninpc** [comment]
> So do I just download the current thing and edit the script? 

just download and use

> I mean, on ver. 3.5 there was a new archive, does it matter?

New files mean that we update with correct comments only

Again: locked patch just add some comments and warnings about bans. This repo just remove it before unlocked patch. When pass some days and no one report ban, the patch are unlocked

Guys, just download and use! WTH you guys need so much info? hahaha

**Comment by Ash3781** [comment]
> Guys, just download and use! WTH you guys need so much info? hahaha

if i try to use the 3.5 patch i get this error in the lutris log, however i made sure to previously recursively change ownership of the entire `/mnt` folder for my user, so this does not really make sense for me:
```
INFO     2023-04-17 14:28:40,940 [game_actions.on_execute_script_clicked:284]:Running /mnt/internal_ssd/Games/genshin-impact/drive_c/gi_menu.bat in the background
lutris-wrapper: /mnt/internal_ssd/Games/genshin-impact/drive_c/gi_menu.bat
Traceback (most recent call last):
File "/usr/share/lutris/bin/lutris-wrapper", line 202, in <module>
main()
File "/usr/share/lutris/bin/lutris-wrapper", line 129, in main
process_pid = subprocess.Popen(args).pid
File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/mnt/internal_ssd/Games/genshin-impact/drive_c/gi_menu.bat'
WARNING  2023-04-17 14:28:40,997 [command.get_return_code:185]:No file /tmp/lutris-119b3cc2-42a3-4223-ba81-4658aaca80f1
DEBUG    2023-04-17 14:28:40,997 [command.on_stop:195]:Process 4309 has terminated with code
```

**Comment by scorninpc** [comment]
1° - why are you using 3.5 if current are 3.6?
2° - do a fresh install if you are getting problem

**Comment by Ash3781** [comment]
i'm sorry, i meant 3.6, i don't want to have to download genshin again, and as far as i know the genshin that lutris currently offer don't include the patch, do i need to create the folder structure for the gi patch files myself then?

**Comment by scorninpc** [comment]
try `chmod  +x GENSHIN_PREFIX/drive_c/gi_path/*.sh`

you can try this lutriis install script https://github.com/zeroday0619/MyLittleLutrisScripts/blob/9bc1735f78e3dda28bc84af5a2b6d5a64d6f6cd7/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/genshin-impact-360.json

**Comment by iambeingtracked** [comment]
> Guys, just download and use! WTH you guys need so much info? hahaha

Sorry about that!

**Comment by Ash3781** [comment]
> try `chmod +x GENSHIN_PREFIX/drive_c/gi_path/*.sh`
> 
> you can try this lutriis install script https://github.com/zeroday0619/MyLittleLutrisScripts/blob/9bc1735f78e3dda28bc84af5a2b6d5a64d6f6cd7/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/genshin-impact-360.json

i got it to work, i had the .bat instead of the .sh file selected as script .-.
