### ISSUE TITLE
[request] honkai: star rail

### ISSUE THREAD

**Issue by lqSky7** [zeroday0619/MyLittleLutrisScripts#14]
i mean it sucks using windows just for one game... would be great if you can patch it

**Comment by elfennani** [comment]
> i mean it sucks using windows just for one game... would be great if you can patch it

I heard Hoyoverse used a new Anti-cheat, so I think the patch will be different than genshin's. Still I would like to learn more about how these patches are made.

**Comment by zeroday0619** [comment]
> > i mean it sucks using windows just for one game... would be great if you can patch it
> 
> I heard Hoyoverse used a new Anti-cheat, so I think the patch will be different than genshin's. Still I would like to learn more about how these patches are made.

Surprisingly, it uses ACE Anti-Cheat

**Comment by niizam** [comment]
The only way I can think is to play it inside the android emulator

**Comment by lqSky7** [comment]
> Surprisingly, it uses ACE Anti-Cheat

So, is it possible to patch? I don't know much about anti-cheats and linux gaming

**Comment by zeroday0619** [comment]
> 
> 
> > Surprisingly, it uses ACE Anti-Cheat
> 
> So, is it possible to patch? I don't know much about anti-cheats and linux gaming

nop...
