### ISSUE TITLE
patch 370

### ISSUE THREAD

**Issue by scorninpc** [zeroday0619/MyLittleLutrisScripts#15]
```
REMOVED
```

btw, tomorow will release patch, and i'll update repo

**Comment by zeroday0619** [comment]
> ```
> REMOVED
> ```
> 
> btw, tomorow will release patch, and i'll update repo

In my opinion. This method is quite risky.

**Comment by scorninpc** [comment]
i undertand your pov, but with patch, servers can validate anticheat too. if devs dont care about patched, maybe they dont care about it too

anyway 1: you are right. that's why this type of new methods need to be played with fresh account for some days

anyway 2: patch dev will release 370 patch tomorow, and i wll post here

**Comment by zeroday0619** [comment]
> i undertand your pov, but with patch, servers can validate anticheat too. if devs dont care about patched, maybe they dont care about it too
> 
> anyway 1: you are right. that's why this type of new methods need to be played with fresh account for some days
> 
> anyway 2: patch dev will release 370 patch tomorow, and i wll post here
> 
> 

Let's split the branch.

**Comment by scorninpc** [comment]
> Let's split the branch.

what do you think about keep this repo only with patch?

if so, i'll up the new patch and edit my first solution

**Comment by zeroday0619** [comment]
> > Let's split the branch.
> 
> what do you think about keep this repo only with patch?
> 
> if so, i'll up the new patch and edit my first solution

not bad

**Comment by scorninpc** [comment]
Done 70becf5a0f0a649f06df1ecdce15290e2de1b22c

To update:
- unpatch
- start launcher
-  update
-  close
-  copy new patch from zip files to gi_patch
- patch
- launch game

To install fresh, use this lutris script https://github.com/zeroday0619/MyLittleLutrisScripts/blob/master/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/genshin-impact-370.json

Some people report that game crash nor show error on screen/after-screen login. Try to go to the folder `Genshin Impact/GenshinImpact_Data/Plugins/` and look for file `Telemetry.dll` and `telemetry.dll`

You need have only `telemetry.dll`, so if this file doesn't exist, rename `Telemetry.dll` to `telemetry.dll`. If exists, just delete `Telemetry.dll`

unlock at 27 May, please use backup or fresh accounts

![image](https://github.com/zeroday0619/MyLittleLutrisScripts/assets/2607849/65aeb6d4-99c0-4643-980d-0c2d63a1d83c)

**Comment by scorninpc** [comment]
unlocked https://github.com/zeroday0619/MyLittleLutrisScripts/commit/f5ea11390990c8cb435a00dfb2905bd73887d29a
