### ISSUE TITLE
Unable to start genshin impact after update

### ISSUE THREAD

**Issue by Ash3781** [zeroday0619/MyLittleLutrisScripts#16]
Hey, there was a update on the genshin impact launcher and after doing it, it tells me this:
![2023-05-24_18-53](https://github.com/zeroday0619/MyLittleLutrisScripts/assets/37660156/b11ce71c-86ad-49fc-a46a-5f2e8c2e525c)
what should i do?

**Comment by Nuker299** [comment]
Because of the update the patch doesn't work, you'll need to wait for an update.
#15 - Info about patch for 3.7

**Comment by scorninpc** [comment]
https://github.com/zeroday0619/MyLittleLutrisScripts/issues/15
