### ISSUE TITLE
Lutris script became useless?

### ISSUE THREAD

**Issue by legluondunet** [zeroday0619/MyLittleLutrisScripts#20]
Hello,
I plan to delete two Lutris scripts installer from this GI Lutris page:
https://lutris.net/games/genshin-impact/
- Wine 3.70 version
and
- Wine Update patch to 3.70 version

cause it is today no more necessary to patch the game on Linux.
Are you agree with that?
I invite you to backup this two scripts if  we need to use them again in a near future.

**Comment by zeroday0619** [comment]
I checked it out. I agree.

**Comment by legluondunet** [comment]
Done!
