### ISSUE TITLE
3.20 Version Related Information

### ISSUE THREAD

**Issue by zeroday0619** [zeroday0619/MyLittleLutrisScripts#3]
### I will upload it after going through the 3.20 version user patch safety verification process.

_Originally posted by @zeroday0619 in https://github.com/zeroday0619/MyLittleLutrisScripts/issues/2#issuecomment-1299737562_

**Comment by SleepyKolosLolya** [comment]
And about how long is that? (I ask just to know what to focus on). tysm btw

**Comment by khjde1207** [comment]
Thank you so much.

**Comment by TheCCraft** [comment]
Thank you

**Comment by kotsmotritnastul** [comment]
thank you for your work, pls dont abandon it, anime game launcher doesnt work for me for some reason, and lutris scripts have not been updated for 2 months, so you are the only source of working scripts.

**Comment by watermelvin** [comment]
@zeroday0619 any chance that this patch and future patches will be added to the lutris installer? Most people installing will try through lutris and may not know to look for the repo or about an anime game launcher.

**Comment by zeroday0619** [comment]
> @zeroday0619 any chance that this patch and future patches will be added to the lutris installer? Most people installing will try through lutris and may not know to look for the repo or about an anime game launcher.

Yes, I'm still registering, but it's not reflected.

**Comment by SleepingPhoenix1** [comment]
How is the progress?
