### ISSUE TITLE
any genshin 3.30 soon?

### ISSUE THREAD

**Issue by akbarfa49** [zeroday0619/MyLittleLutrisScripts#4]

**Comment by zeroday0619** [comment]
yes, please wait a little longer

**Comment by scorninpc** [comment]
i tryed to see if added new domains to block or something else, but no good start. I dont know nor understand the diffs of unity player, but if you can give some tips or do some checklist i can try some steps

**Comment by dino8890** [comment]
Indeed, sharing knowledge on how do you obtain binary changes to `UnityPlayer.exe` and `xlua.dll` would benefit the Linux Genshin community greatly. It would enable other people to derive patches themselves, and it would also relieve you of pressure and make sure Genshin still works on Linux after or if you get tired of maintaining this repo.

**Comment by zeroday0619** [comment]
> Indeed, sharing knowledge on how do you obtain binary changes to `UnityPlayer.exe` and `xlua.dll` would benefit the Linux Genshin community greatly. It would enable other people to derive patches themselves, and it would also relieve you of pressure and make sure Genshin still works on Linux after or if you get tired of maintaining this repo.

I am not the creator of this patch. 
For reference, the creator of this patch warned: 

miHoYo reserves the right to distribute files. Please do not share any game data in public.

For your own sake: 
Please do not share this project in public.
Reduces the risk of this project to be taken down or used against our reverse-engineering efforts

Solution: 
Use indirect/redirect links and private messages

Please do not abuse this project for cheating. We just want to play the game.

For project contributors: 
Beware that your log files may contain personal information, such as MAC addresses or login data.

**Comment by scorninpc** [comment]
Patch was released

if i create the zip and pull, you merge?

**Comment by ezequielramos** [comment]
Please @scorninpc. I guess everyone will already thank you for the PR with the zip file to plugin and play the game :)

**Comment by zeroday0619** [comment]
@scorninpc `As usual, please use only testing accounts until the patch is confirmed working. If everything goes well, patch unlock will be on 10 December.`

**Comment by zeroday0619** [comment]
@scorninpc I am not responsible for any damage caused by this.

**Comment by zeroday0619** [comment]
@scorninpc @ezequielramos 
You can package it yourself with this.
https://gist.github.com/zeroday0619/3942d88743319e9c0638d7693f4fbb08

**Comment by scorninpc** [comment]
i'm downloads 1.5G of repo =/ 
i'll do a PR, you decide if you merge.

Thank you for package script

**Comment by scorninpc** [comment]
Done #5 

@zeroday0619 

Can i ask where did you found this script? this has some new scripts from this version, that you haven't created yet!

And, why not create a separated repo for genshin only? so large

```FOR REAL, GUYS```

this appear to use some new dlls to protect. So, create or use a second account for a few days before start use main account

**Comment by zeroday0619** [comment]
@scorninpc It's meaningless, but we're maintaining the existing repo to avoid being identified as a Genshin Impact user patch repository.

**Comment by zeroday0619** [comment]
That's why I didn't want to use the word Genshin Impact, but it's already too late lol.

**Comment by scorninpc** [comment]
> @scorninpc It's meaningless, but we're maintaining the existing repo to avoid being identified as a Genshin Impact user patch repository.

Ah! this is real and make 100% sense

**Comment by zeroday0619** [comment]
I'll merge as soon as stability is confirmed. Thanks for your contribution.

**Comment by scorninpc** [comment]
Updated with CN patchs and without exits. I think this can be closed!
