### ISSUE TITLE
any genshin 3.40 soon?

### ISSUE THREAD

**Issue by 15767905786** [zeroday0619/MyLittleLutrisScripts#7]
any genshin 3.40 soon?

**Comment by zeroday0619** [comment]
yes i will update it soon.

**Comment by khjde1207** [comment]
thank you so much

**Comment by JechtShinryaku** [comment]
> yes i will update it soon.

yay

**Comment by scorninpc** [comment]
updated 7abf681899c2d54f4be55d43cdd5ac19ede933e6

*please remember! Only test accounts*

**Comment by kotsmotritnastul** [comment]
if someone tested it pls provide some feedback.

**Comment by scorninpc** [comment]
lol ![image](https://user-images.githubusercontent.com/2607849/213326852-420dca79-f204-4495-9042-0c5346a73595.png)

**Comment by sinkapoy** [comment]
I've played for some time (about 1.5h+), got 4th rank. Everything seems ok.

**Comment by shtrophic** [comment]
Has it even happened already that someone got banned over using a patch like this?

**Comment by scorninpc** [comment]
never reported, but be careful. play with new account for some week

**Comment by zeroday0619** [comment]
Sorry for the late update.
https://github.com/zeroday0619/MyLittleLutrisScripts/commit/d7d4c1705dd7c94a888c11996bede2aa6d227376
