### ISSUE TITLE
Is it nessesary to patch Genshin Impact xlua.dll and UnityPlayer.dll?

### ISSUE THREAD

**Issue by gorgiaxx** [zeroday0619/MyLittleLutrisScripts#8]
interim measures

**Comment by gorgiaxx** [comment]
I can run Genshin Impact v3.40 with the v3.30 patch script @scorninpc

**Comment by zeroday0619** [comment]
@gorgiaxx Please do not post technical analysis here

**Comment by gorgiaxx** [comment]
i figured it out

**Comment by scorninpc** [comment]
i think this can be deleted or edited by @gorgiaxx

**Comment by cybik** [comment]
Seconded, please get this analysis removed.

**Comment by zeroday0619** [comment]
took temporary action
